TemplateTasks:
- name: Basic Task Template
  description: Perform a task every day
  group: Self    # Self, Work, Family, Cleaning, Apartment, Event, Used for view group and colors
  frequency: daily    # daily, weekly, once
  start_time: 08:00   # 24 hour clock , xx means no start time
  end_time: 09:00   # 24 hour clock, xx means no end time
  priority: high    # low, med, high, mandatory
  completed: false
  date: '2024-05-15' # YYYY-MM-DD

- name: Master Task Template
  description: Master task template
  report_frequency: weekly    # day, week, one, month, year
  reports:    # empty obj to hold the reports  
  sub_tasks:    # empty obj to hold the subtasks
  priority: med    # low, med, high, mandatory
  completed: false
  due_date: '2024-05-15' # YYYY-MM-DD
  color: blue    # color code for the task
  
- name: Sub Task Template
  description: Sub task template
  note: Sub task note, anything can go here
  objectives:   #empty obj to hold the actionable objectives obj id -> table entry with a seperate table
  priority: low    # low, med, high, mandatory
  completed: false
  sessions:   # empty obj to hold the sessions 
  due_date: '2024-05-16' # YYYY-MM-DD

- name: Objective Template
  description: Objective task template
  action: Objective action
  state: pending    # pending, in_progress, completed

  - name: Session Template
  description: Session task template
  note: Session note, anything can go here
  objectives:   #empty obj to hold the objectives to check off the subtask
  date: '2024-05-16' # YYYY-MM-DD
  start_time: 08:00   # 24 hour clock
  end_time: 09:00   # 24 hour clock

- name: Report Template
  description: Report task template
  report: Report on the Master/Appointment Task, anything can go here
  state: pending    # pending, completed

- name: Appointment Template
  description: Appointment task template
  note: Appointment pre note  # have ai input info
  reports:  #  empty obj for report once triggered, have ai read to see if any important info to notes
  location: Appointment location  # maps location? or address
  alarm: 30    # in minutes + travel time, xx means no alarm
  travel_time: 30    # in minutes, want to load uber and lyft rate compare and pick cheapest
  time: 08:00    # 24 hour clock
  date: '2024-05-15' # YYYY-MM-DD once time passes trigger Report

Database:
  -notes: journal 1 ai 

  primary secondary key
  t3 stack
  t4 stack

ui right 1/4
schedule
llm read journal entry 